### ISSUE TITLE
Event loop is closed

### ISSUE THREAD

**Issue by Foxlider** [sleibrock/discord-bots#5]
I created a bot base on the DumbBot you created on the tutorial for Discord.
But everytime I try to run i get the Event loop is closed error
I tried many bots, many run functions i found but none of them works. 
Here is the traceback console : 

```
[foxlibot     @ 12:37:23] Local blacklist not found    
Caught an exception: Event loop is closed
foxlibot quitting
Traceback (most recent call last):
  File "C:\Users\allon\Documents\Dev\Python\FoxliBOT\FoxliBOT.py", line 161, in <module>
    d.run()
  File "c:\users\allon\documents\dev\python\foxlibot\Bot.py", line 318, in run
    #    quit()
  File "c:\users\allon\miniconda3\lib\asyncio\base_events.py", line 443, in run_until_complete
    self._check_closed()
  File "c:\users\allon\miniconda3\lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

EDIT : It was just miniconda 
Works with python 3.6

**Comment by ste5e99** [comment]
That is quite strange. Using Anaconda raises this error? I'll write a note about this in the README if that's the case.

**Comment by Foxlider** [comment]
Maybe you need to check if I made an error in installing Anaconda (I don't
think it's the case since I made a clean install this morning)

**Comment by ste5e99** [comment]
I'll try doing an Anaconda install myself and see if I can get the same issue. For the time being I'm developing with Python 3.6 and the latest libraries for Discord.py, so maybe there's an issue with that.

**Comment by ste5e99** [comment]
Hm, I can't seem to duplicate this with a normal 64-bit Anaconda install. Here's the steps I took:

```
git clone https://github.com/sleibrock/discord-bots
cd discord-bots
pip install -r requirements.txt
python bots/dumb-bot.py
```
This seems to work for the most part. `pip` under Anaconda seems to be fully compliant with other PyPI packages so there's no problem here that I can see.
```
python
>>> import discord
<module 'discord' from 'C:\\Conda\\lib\\site-packages\\discord\\__init__.py'>
```
Do you have any source code that I could look at to examine as well as the output of your `pip freeze` command? Did you install using `virtualenv`?

**Comment by Foxlider** [comment]
In fact I deleted it all and started again from scrap
